### ISSUE TITLE
List what citation.IDs to submit first

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/IPCC-EFDB-integration#1]
@teixeirak, here is the list of citation ID that have 95%CI in MEASUREMENTS. 
You can add in this issue (or we can create a new file) the other citations you'd like to submit first.

- [x] Archibald_2009_doiv
- [x] Chave_2008_aepa (but ANPP_woody_stem variable needs clarification, issue #3)
- [ ] ~~Goulden_1996_eocd~~ (doesn't make it through to ForC simplified)
- [ ] Keith_2009_mmce (would be good to revisit for more info)
- [ ] Keller_2001_beit (first resolve [this issue](https://github.com/forc-db/ForC/issues/217))
- [x] Lin_2012_tvia
- [x] Meakem_2017_rots (but ANPP_woody_stem variable needs clarification, issue #3 )
- [x] Ngo_2013_csip
- [ ] Orihuela-Belmonte_2013_csaa (has some 95% CI info that hasn't been entered)
- [ ] Rice_2004_cbav (would be good to revisit for more info)
- [ ] Saleska_2003_ciaf (first resolve [this issue](https://github.com/forc-db/ForC/issues/217))
- [ ] Toky_1983_ssfs (Not now-- involves suspected duplicates)
- [x] Uhl_1984_sand (but ANPP_woody_stem variable needs clarification, issue #3 )

Other priorities, not yet reviewed:
- [x] Lutz_2018_giol
- [ ] Johnson_2018_csss
- [x] Gonzalez-Akre_2016_potm

**Comment by teixeirak** [comment]
@ValentineHerr, checkmarks above indicate that I approve sending the study, but still want to check the mapping.

**Comment by teixeirak** [comment]
@ValentineHerr , I'm done reviewing this list, which has 6 studies that are ready. I added a few more ForestGEO studies that I'm quite familiar with to the list, in case we have time for more.

**Comment by teixeirak** [comment]
ready to go following re-run:
- Meakem
- Uhl
- Lin
-

**Comment by teixeirak** [comment]
@ValentineHerr ,  the Lutz study included 48 plots, all of which made it through to ForC simplified, but only 31 made it through to the file for review. Do you know what's going on? 

Also, all have n and sd in Measurements, yet CIs are only calculated for some.

Finally, (for me), `n`'s may be wrong in measurements.

**Comment by ValentineHerr** [comment]
I'll check for Lutz

**Comment by ValentineHerr** [comment]
I see only 35 measurements in for Lutz_2018_giol in ForC_simplified, and 4 of them have a "1" in `suspected.duplicate`

**Comment by teixeirak** [comment]
Oh, sorry, you're right. I was accidently looking at  ForC_measurements

**Comment by teixeirak** [comment]
@ValentineHerr , in addition to the ones we sent yesterday, we can send:
- Archibald
-

**Comment by teixeirak** [comment]
I believe we can close this issue.
