### ISSUE TITLE
checklist to finish paper

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#39]
- [x] missing references
- [x] add some more recent references
- [x] #40 
- [x] #41 
- [x] include climwin version used to ID climate outliers (https://github.com/forc-db/ForC/commit/21e8b7e33b735473d3b4913714b7d2c496d4b8b5)
- [x] confirm/find ref for this statement: "*tropical countries are more likely to apply Tier 1 methodology that bases forest C budgets on previously existing data [@ref]."
- [x] can this statement be expressed according to Tiers? "*to records from countries relying on existing records (as opposed to regular collection of new data through forest inventories)*"
- [x] #42 
- [x] #43 
- [x] #44 
- [x] update code pulling out n records by variable (~l. 150-162)
- [x] check that conclusions from histogram figure don't change with updated results
- [x] #45
- [x] #46 
- [x] #48 
- [x] #49 
- [x] incorporate Sandro's edits
- [x] change "accounting" (including in title)
- [x] "transferred to EFDB" --> "submitted to EFDB"
- [x] #51
- [x] integrate Susan's comments
- [x] properly insert footnotes in appendix b table
- [x] fix references that aren't rendering

**Comment by teixeirak** [comment]
moved a couple items to #54
